name: ooghatsharei
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter_spinkit: ^5.2.1
  quickalert: ^1.1.0
  share_plus: ^10.1.4
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  shamsi_date: ^1.0.4
  flutter_widget_from_html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
      - family: Peyda-B
        fonts:
          - asset: assets/fonts/PeydaFaNum-Black.ttf
      - family: Peyda-M
        fonts:
          - asset: assets/fonts/PeydaFaNum-Medium.ttf    
      - family: Peyda-L
        fonts:
          - asset: assets/fonts/PeydaFaNum-Light.ttf
      - family: Peyda-R
        fonts:
          - asset: assets/fonts/PeydaFaNum-Regular.ttf   
      - family: Peyda-SB
        fonts:
          - asset: assets/fonts/PeydaFaNum-SemiBold.ttf  